// resources/js/pages/settings/profile/sections/identity-summary.tsx

import type { ReactElement } from 'react';
import { DoctorAvatar } from '@/components/doctor-avatar';

const ROLE_LABELS: Record<string, string> = {
    doctor: 'Physician',
    nurse: 'Nurse',
    hr: 'HR Officer',
    admin: 'Administrator',
    user: 'Patient',
};

interface IdentitySummaryProps {
    firstName: string;
    lastName: string;
    email: string;
    roles: string[];
    clientNumber: string | null;
    memberSince: string | null;
    /**
     * The signed-in doctor's headshot, from `auth.user.photo_url`. Null for
     * every other role and for a doctor with no photo — the strip then shows
     * initials, as it always has.
     */
    photoUrl?: string | null;
}

/**
 * The read-only identity strip above the profile form.
 *
 * `client_number` is generated by PatientProfile::booted() and is the number
 * the clinic desk asks for over the phone — so it is shown prominently and is
 * deliberately not editable anywhere in this UI.
 */
export function IdentitySummary({
    firstName,
    lastName,
    email,
    roles,
    clientNumber,
    memberSince,
    photoUrl = null,
}: IdentitySummaryProps): ReactElement {
    const displayName = `${firstName} ${lastName}`.trim() || email;

    const initials =
        displayName
            .split(' ')
            .slice(0, 2)
            .map((part) => part[0]?.toUpperCase() ?? '')
            .join('') || '?';

    const roleLabel = roles
        .map((role) => ROLE_LABELS[role] ?? role)
        .join(' · ');

    return (
        <section className="wc-settings-identity">
            {/*
              The same avatar the topbar, the public directory, the profile page
              and the booking picker render — one place decides photo-or-
              initials, so this page cannot be the one that keeps showing
              initials for a doctor who has uploaded a photograph.
            */}
            <DoctorAvatar
                photoUrl={photoUrl}
                initials={initials}
                color="var(--wc-blue-600)"
                // Empty, so the <img> is decorative: the heading beside it
                // already names the person, and an alt repeating it would have
                // a screen reader read them twice. This is what the
                // aria-hidden on the initials did before.
                name=""
                size={56}
                className="wc-settings-identity-avatar"
                // The strip has always used the larger step at this size, in
                // the body font; DoctorAvatar's own bucket for a 56px box is
                // one step below it, in the display font. A doctor with no
                // photograph must see the strip they saw yesterday.
                style={{
                    fontSize: 'var(--text-lg)',
                    fontFamily: 'var(--font-sans)',
                }}
            />

            <div className="wc-settings-identity-body">
                <h2 className="wc-settings-identity-name">{displayName}</h2>
                <p className="wc-settings-identity-meta">
                    {roleLabel && <span>{roleLabel}</span>}
                    <span>{email}</span>
                </p>
            </div>

            <dl className="wc-settings-identity-facts">
                {clientNumber && (
                    <div>
                        <dt>Client number</dt>
                        <dd>{clientNumber}</dd>
                    </div>
                )}
                {memberSince && (
                    <div>
                        <dt>Registered</dt>
                        <dd>
                            {new Date(memberSince).toLocaleDateString('en-PH', {
                                year: 'numeric',
                                month: 'short',
                                day: 'numeric',
                            })}
                        </dd>
                    </div>
                )}
            </dl>
        </section>
    );
}
