<?php

namespace App\Http\Controllers\Settings;

use App\Http\Controllers\Controller;
use App\Http\Requests\Settings\ProfileDeleteRequest;
use App\Http\Requests\Settings\ProfileUpdateRequest;
use App\Models\User;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Inertia\Inertia;
use Inertia\Response;

class ProfileController extends Controller
{
    /**
     * Show the user's profile settings page.
     */
    public function edit(Request $request): Response
    {
        /** @var User $user */
        $user = $request->user();
        $profile = $user->profile;

        return Inertia::render('settings/profile/index', [
            'mustVerifyEmail' => $user instanceof MustVerifyEmail,
            // Passed explicitly rather than read off the shared auth prop: this
            // page is the only route through which an unverified account can
            // request a new link, so whether the banner shows must not depend on
            // a middleware payload the page does not own.
            'emailVerified' => $user->hasVerifiedEmail(),
            'status' => $request->session()->get('status'),
            'profile' => [
                'first_name' => $profile?->first_name ?? '',
                'last_name' => $profile?->last_name ?? '',
                'email' => $user->email,
                'contact_number' => $profile?->contact_number ?? '',
                'address' => $profile?->address ?? '',
                'company' => $profile?->company ?? '',
                'gender' => $profile?->gender ?? '',
                // The form binds a native <input type="date">, which only
                // accepts Y-m-d. The cast hands back a Carbon instance, so
                // formatting here rather than in the component keeps the page
                // from having to know about the cast.
                'birthdate' => $profile?->birthdate?->format('Y-m-d') ?? '',
                'civil_status' => $profile?->civil_status ?? '',
            ],
            // Read-only identity, shown so the patient can quote it to the
            // clinic. Generated by PatientProfile::booted() and deliberately
            // not editable.
            'clientNumber' => $profile?->client_number,
            'memberSince' => $user->created_at?->toISOString(),
            'roles' => $user->getRoleNames()->toArray(),
            'canDeleteAccount' => $user->canCloseOwnAccount(),
        ]);
    }

    /**
     * Update the user's profile information.
     *
     * Names live on patient_profiles, not users — there is no users.name
     * column, and User::$fillable is only [email, password, is_active].
     * Writing the name through the user model (as this previously did)
     * silently dropped it.
     */
    public function update(ProfileUpdateRequest $request): RedirectResponse
    {
        $validated = $request->validated();

        /** @var User $user */
        $user = $request->user();

        DB::transaction(function () use ($user, $validated) {
            $user->email = $validated['email'];

            // Changing the email un-verifies it; User implements MustVerifyEmail,
            // so this genuinely gates the doctor/hr/admin routes.
            if ($user->isDirty('email')) {
                $user->email_verified_at = null;
            }

            $user->save();

            $user->profile()->updateOrCreate(
                ['user_id' => $user->id],
                [
                    'first_name' => $validated['first_name'],
                    'last_name' => $validated['last_name'],
                    // Already normalised to null by
                    // ProfileUpdateRequest::prepareForValidation(), so clearing
                    // a field clears the column rather than storing ''.
                    'contact_number' => $validated['contact_number'],
                    'address' => $validated['address'],
                    'company' => $validated['company'],
                    'gender' => $validated['gender'],
                    'birthdate' => $validated['birthdate'],
                    'civil_status' => $validated['civil_status'],
                ]
            );
        });

        return to_route('profile.edit')->with('success', 'Your profile has been updated.');
    }

    /**
     * Close the user's account.
     *
     * This used to be `$user->delete()` against a model with no SoftDeletes,
     * and six ON DELETE CASCADE keys turned it into the most destructive
     * endpoint in the application: it took the account holder's allergies,
     * diagnoses and document rows with it, left the uploaded files orphaned on
     * disk, and left the `patients` row alive but stripped and unreachable.
     * A patient could destroy their own medical record from a settings page.
     *
     * `User::closeAccount()` now scrubs the credentials and retires the row
     * while the clinical record stays intact — see the docblock there for what
     * is retained and why that is not the same as erasure.
     */
    public function destroy(ProfileDeleteRequest $request): RedirectResponse
    {
        /** @var User $user */
        $user = $request->user();

        if (! $user->canCloseOwnAccount()) {
            return back()->withErrors([
                'password' => 'Staff accounts cannot be self-closed because they are attached to clinical records. Ask an administrator to deactivate the account instead.',
            ]);
        }

        Auth::logout();

        $user->closeAccount();

        $request->session()->invalidate();
        $request->session()->regenerateToken();

        return redirect('/');
    }
}
